#!/bin/bash

custom_randr() { default_randr "$@"; }

# ** load config
CPATH="${XDG_CONFIG_HOME:-$HOME/.config}/ferrydust"
if [ -f "$CPATH/ferryrandr.rc" ]; then
  source "$CPATH/ferryrandr.rc"
fi

# ** fix options missing in config
# 
[ -z $POSITION] && POSITION="left-of"
# maximum number of outputs the viceo card can handle
[ -z $MAX_ENABLED_OUTPUTS] && MAX_ENABLED_OUTPUTS=2
# all available outputs
[ -z $OUTPUTS] && OUTPUTS=$(xrandr |awk '$2 ~ /connected/ {print $1}')
# your notebook LVDS monitor
[ -z $DEFAULT_OUTPUT] && DEFAULT_OUTPUT=$(sed -ne 's/.*\(LVDS[^ ]*\).*/\1/p' <<<$OUTPUTS)
# remove default from list
OUTPUTS=${OUTPUTS#$DEFAULT_OUTPUT}
# get info from xrandr
XRANDR=`xrandr`
# number of actually connected outputs
NUM_CONNECTED=$(echo "$XRANDR" | grep " connected" | wc -l)

default_randr() {
  # ** disable default when to many outputs are connected
  if [ $NUM_CONNECTED -gt $MAX_ENABLED_OUTPUTS ]; then
    echo "More than $MAX_ENABLED_OUTPUTS displays connected, disabling LVDS."
    xrandr --output $DEFAULT_OUTPUT --off
  else
    if [[ $XRANDR == *$DEFAULT_OUTPUT\ connected\ \(* ]]; then
      echo "Setting LVDS to auto"
      xrandr --output $DEFAULT_OUTPUT --auto
    fi
    LAST=$DEFAULT_OUTPUT
  fi

  # ** set everything but internal
  i=0
  for CURRENT in $OUTPUTS; do
    if [[ $XRANDR == *$CURRENT\ connected*  ]]; then
      if [ $i -lt $MAX_ENABLED_OUTPUTS ]; then
        if [[ $XRANDR == *$CURRENT\ connected\ \(* ]]; then
          echo "Setting $CURRENT to auto ($POSITION $LAST)"
          xrandr --output $CURRENT --auto --$POSITION $LAST
        fi
        LAST=$CURRENT
      fi
      let i++
    else
      echo "Disabling unconnected display $CURRENT"
      xrandr --output $CURRENT --off
    fi
  done
}

custom_randr