#!/bin/sh

source ETCPREFIX/acpithings.rc

# TODO multiple batteries

sct=$(cat /sys/devices/platform/smapi/BAT0/start_charge_thresh)

if [ "$sct" -lt 81 ]; then
    echo $CHARGE_START_HIGH > /sys/devices/platform/smapi/BAT0/start_charge_thresh
    echo $CHARGE_END_HIGH > /sys/devices/platform/smapi/BAT0/stop_charge_thresh
else
    echo $CHARGE_START_LOW > /sys/devices/platform/smapi/BAT0/start_charge_thresh
    echo $CHARGE_END_LOW > /sys/devices/platform/smapi/BAT0/stop_charge_thresh
fi